version: 2
jobs:
   build:
     docker:
       - image: anhill/circleci-node6.14.2-npm
     steps:
       - checkout
       - run: python helloWorld.py
       - run:
          command: |
            git clone git@github.com:anhill-D2L/files.git
            chmod +x files/*.*
            ./files/myscript.sh
            ./files/test1.sh
            ./files/test2.sh
            ./files/test1.sh
workflows:
  version: 2
  deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master