version: 2
jobs:
   build:
     docker:
       - image: anhill/circleci-node6.14.2-npm
     steps:
       - checkout
       - run: python helloWorld.py
       - run: echo "echo statement"
       - run: print_five
workflows:
  version: 2
  deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master