version: 2
jobs:
   build:
     docker:
       - image: anhill/circleci-node6.14.2-npm
     steps:
       - checkout
       - run: python helloWorld.py
       - run: echo "echo statement"
       - run: print_five () { echo 1; echo 2; echo 3; echo 4; echo 5;}
       - run: print_five
workflows:
  version: 2
  deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master